In [1]:
import duckdb
import pandas as pd

result = duckdb.sql("""
    SELECT COUNT(*) as total_rows, 
           MIN(t_dat) as earliest_date, 
           MAX(t_dat) as latest_date
    FROM '../data/raw/transactions_train.csv'
""").df()

result

   total_rows earliest_date latest_date
0    31788324    2018-09-20  2020-09-22

In [2]:
trousers_ts = duckdb.sql("""
    SELECT 
        t.t_dat AS date,
        tr.fit_category,
        COUNT(*) AS units_sold
    FROM '../data/raw/transactions_train.csv' t
    JOIN '../data/interim/trousers_tagged.csv' tr
        ON t.article_id = tr.article_id
    GROUP BY t.t_dat, tr.fit_category
    ORDER BY t.t_dat
""").df()

print(trousers_ts.shape)
trousers_ts.head(10)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

(3670, 3)

        date  fit_category  units_sold
0 2018-09-20       tapered        1853
1 2018-09-20      straight         715
2 2018-09-20   skinny_slim        5007
3 2018-09-20  wide_relaxed         242
4 2018-09-20       regular          97
5 2018-09-21   skinny_slim        4795
6 2018-09-21       regular          87
7 2018-09-21      straight         738
8 2018-09-21  wide_relaxed         262
9 2018-09-21       tapered        1718

In [3]:
jackets_ts = duckdb.sql("""
    SELECT 
        t.t_dat AS date,
        j.style_category,
        COUNT(*) AS units_sold
    FROM '../data/raw/transactions_train.csv' t
    JOIN '../data/interim/jackets_tagged.csv' j
        ON t.article_id = j.article_id
    GROUP BY t.t_dat, j.style_category
    ORDER BY t.t_dat
""").df()

print(jackets_ts.shape)
jackets_ts.head(10)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

(2200, 3)

        date style_category  units_sold
0 2018-09-20         bomber          20
1 2018-09-20          denim         105
2 2018-09-20  leather_biker         168
3 2018-09-21         bomber          33
4 2018-09-21          denim          96
5 2018-09-21  leather_biker         167
6 2018-09-22  leather_biker          37
7 2018-09-22          denim          46
8 2018-09-22         bomber           9
9 2018-09-23         bomber          32

In [4]:
trousers_ts.to_csv('../data/processed/trousers_daily_sales.csv', index=False)
jackets_ts.to_csv('../data/processed/jackets_daily_sales.csv', index=False)
print("Saved both time series to data/processed/")

Saved both time series to data/processed/